name: $(GITVERSION_FullSemVer)

trigger:
  branches:
    include:
      - master
      - develop
      - release/*
      - feature/*
      - bugfix/*
  paths:
    include:
      - '*'
    exclude:
     - 'azure-pipelines.yml'

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'choco install dotnetcore-6.0-sdk'
- task: gitversion/setup@0
  inputs:
    versionSpec: '5.10.0'
- task: gitversion/execute@0
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    useConfigFile: true
    configFilePath: 'GitVersion.yml'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    projects: '**/*.csproj' 
    vstsFeed: 'ff478692-09f4-406d-8d3e-4566cb81b0db'
    includeNuGetOrg: false
    versioningScheme: byBuildNumber
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) /p:Version=$(GitVersion.SemVer)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test $(buildConfiguration)'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack' 
  inputs: 
    command: pack
    packagesToPack: '**/*.csproj' 
    nobuild: true 
    versioningScheme: byEnvVar 
    versionEnvVar: GitVersion.SemVer

- task: DotNetCoreCLI@2 
  displayName: 'dotnet nuget push' 
  inputs: 
    command: push 
    publishVstsFeed: 'ff478692-09f4-406d-8d3e-4566cb81b0db' 
    versioningScheme: byBuildNumber
