name: $(GITVERSION_FullSemVer)

trigger:
  branches:
    include:
      - main
      - feature/*
      - develop/*
  paths:
    include:
      - '*'
    exclude:
     - 'azure-pipelines.yml'
pr:
  - main
  - develop
  - feature/* 
pool:
  vmImage: 'ubuntu-latest'
parameters:
  - name: generateTag
    type: boolean
    default: false
  - name: commentTag
    type: string
    default: 'update version'

variables:
  buildConfiguration: 'Release' 
  GitVersion.SemVer: ''
steps :
  - checkout: self
    #persistCredentials: true
    fetchDepth: 0
  - task: ShellScript@2
    condition: and(succeeded(), eq('${{ parameters.generateTag }}', 'true'))
    inputs:
      scriptPath: 'git_taging.sh'      
      #args: -commentTag ${{ parameters.commentTag }}