//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genzai.WebCore.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebCoreLocalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebCoreLocalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genzai.WebCore.Locales.WebCoreLocalStrings", typeof(WebCoreLocalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save changes to database..
        /// </summary>
        public static string DataBaseErrorMessage {
            get {
                return ResourceManager.GetString("DataBaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default entities cannot be mofidied..
        /// </summary>
        public static string DefaultEntityMessage {
            get {
                return ResourceManager.GetString("DefaultEntityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID cannot equal a default one..
        /// </summary>
        public static string DefaultIdMessage {
            get {
                return ResourceManager.GetString("DefaultIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot equal a default one..
        /// </summary>
        public static string DefaultNameMessage {
            get {
                return ResourceManager.GetString("DefaultNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists an entity with same code.
        /// </summary>
        public static string DuplicatedEntityCodeMessage {
            get {
                return ResourceManager.GetString("DuplicatedEntityCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists an entity with same ID.
        /// </summary>
        public static string DuplicatedEntityIdMessage {
            get {
                return ResourceManager.GetString("DuplicatedEntityIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists an entity with same name.
        /// </summary>
        public static string DuplicatedEntityNameMessDuplicatedEntityNameMessage {
            get {
                return ResourceManager.GetString("DuplicatedEntityNameMessDuplicatedEntityNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; must be empty.
        /// </summary>
        public static string EmptyFieldMessage {
            get {
                return ResourceManager.GetString("EmptyFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be empty.
        /// </summary>
        public static string FieldNotEmptyMessage {
            get {
                return ResourceManager.GetString("FieldNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email in field &apos;{0}&apos;.
        /// </summary>
        public static string IncorrectMailMessage {
            get {
                return ResourceManager.GetString("IncorrectMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in field &apos;{0}.
        /// </summary>
        public static string InvalidValueMessage {
            get {
                return ResourceManager.GetString("InvalidValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of field &apos;{0}&apos; is {1}.
        /// </summary>
        public static string MaxLengthMessage {
            get {
                return ResourceManager.GetString("MaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max size of field &apos;{0}&apos; is {1}.
        /// </summary>
        public static string MaxSizeMessage {
            get {
                return ResourceManager.GetString("MaxSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} must be equal or greater than zero. | ParamEqualOrMoreThanZero.
        /// </summary>
        public static string ParamEqualOrMoreThanZero {
            get {
                return ResourceManager.GetString("ParamEqualOrMoreThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} cannot be null. | ParameterIsNull.
        /// </summary>
        public static string ParameterIsNull {
            get {
                return ResourceManager.GetString("ParameterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is required | RequiredFieldMessage.
        /// </summary>
        public static string RequiredFieldMessage {
            get {
                return ResourceManager.GetString("RequiredFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be before end date.
        /// </summary>
        public static string StartDateAfterEndDateMessage {
            get {
                return ResourceManager.GetString("StartDateAfterEndDateMessage", resourceCulture);
            }
        }
    }
}
